### ISSUE TITLE
Research Gemini / Create Prototype to make API calls

### ISSUE THREAD

**Issue by RobertLikesCoding** [RobertLikesCoding/QuizCraft#3]
## Task Overview
- [x]  Outline restrictions with 'free' tier
- [x]  Determine character limits with prompts - 1 million tokens per minute.
- [x]  Determine call limits  - 15 Request per minute, 1500 Request per day
- [x] Prototype making calls to API
- [x] Create .env to store API tokens for calls
